### ISSUE TITLE
Incorrect derivation of Master Secret (draft 20 implementation)

### ISSUE THREAD

**Issue by muhammad-usama-sardar** [Inria-Prosecco/reftls#6]
In [ProVerif modeling of draft 20](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl), the [master secret derivation](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl#L251) is implemented wrongly:

       let ms =   hkdf_extract(hs , zero) in

Essentially, the model skips the following step shown in the Key Schedule (cf. diagram showing full key derivation schedule on page 88 in [Sec. 7.1 of draft 20](https://datatracker.ietf.org/doc/html/draft-ietf-tls-tls13-20#section-7.1)):
`Derive-Secret(., "derived", "")`

Hence, it should be: 

       let ms =   hkdf_extract(extra , zero) in

**Comment by bruno-blanchet** [comment]
Fixed as you suggested, thanks for the report.
