### ISSUE TITLE
Incorrect implementation of salts for Handshake Secret and Master Secret (draft 20 implementation)

### ISSUE THREAD

**Issue by muhammad-usama-sardar** [Inria-Prosecco/reftls#7]
### Salt for Handshake Secret
In [ProVerif modeling of draft 20](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl), the [salt for Handshake Secret derivation](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl#L246) is implemented wrongly:

       let extra = derive_secret(es,tls13_derived,hash(StrongHash,zero)) in

Essentially, instead of implementing `Derive-Secret(es, "derived", "")`, the model implements `Derive-Secret(es, "derived", hash(""))`. Since `Derive-Secret` by definition includes hash over Messages, the above formal model results in an additional iteration of hash. 

Hence, in accordance with [Sec. 7.1 of draft 20](https://datatracker.ietf.org/doc/html/draft-ietf-tls-tls13-20#section-7.1), it should be: 

       let extra = derive_secret(es,tls13_derived,zero) in

### Salt for Master Secret
Same applies to [salt for Master Secret](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl#L250):

       let extra = derive_secret(hs,tls13_derived,hash(StrongHash,zero)) in
which should be 

       let extra = derive_secret(hs,tls13_derived,zero) in

**Comment by bruno-blanchet** [comment]
Fixed as you suggested. Thanks for the report.
