### ISSUE TITLE
Unused subprocess (draft 20 implementation)

### ISSUE THREAD

**Issue by muhammad-usama-sardar** [Inria-Prosecco/reftls#9]
In [ProVerif modeling of draft 20](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl), no piece of code in any process ever uses the subprocess `fixedLongTermKeys`. Hence, the [following code snippet](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl#L174-L194) serves no purpose other than adding more confusion to the auditors. 
```
let fixedLongTermKeys() = 
     new skA: privkey;
     new skB: privkey;
     new skM: privkey;
     let pkA = pk(skA) in
     let pkB = pk(skB) in
     let pkM = pk(skM) in
     new pskAB: bitstring;
     new pskAM: bitstring;
     new pskMB: bitstring;
     insert longTermKeys(A,skA,pkA);
     insert longTermKeys(B,skB,pkB);
     insert longTermKeys(M,skM,pkM);
     insert preSharedKeys(A,B,PSK(pskAB));     
     insert preSharedKeys(A,M,PSK(pskAM));     
     insert preSharedKeys(M,B,PSK(pskMB));     
     event WeakOrCompromisedKey(NoPubKey);
     event WeakOrCompromisedKey(pkM);
     event CompromisedPreSharedKey(PSK(pskAM));
     event CompromisedPreSharedKey(PSK(pskMB));
     out(io,(skM,pskAM,pskMB)).
```

This was checked by defining a simple event `test2` and placing this event at the very beginning of the subprocess. Then writing a simple reachability query `query event (test2).` confirms that it is not reachable.

**Comment by bruno-blanchet** [comment]
It is true that fixedLongTermKeys is currently not used. It is a possible replacement for the process longTermKeysProc that the people can use by modifying the main process in tls13-draft20-only.pv. (longTermKeysProc provides dynamic long-term keys,   while fixedLongTermKeys provides fixed long-term keys as the name says.)
